COINES_INSTALL_PATH ?= ../../../..

EXAMPLE_FILE ?= bmm350_interrupt.c

API_LOCATION ?= ../..

C_SRCS += \
$(API_LOCATION)/bmm350.c \
../common/common.c

INCLUDEPATHS += \
$(API_LOCATION) \
../common

TARGET = MCU_APP30

include $(COINES_INSTALL_PATH)/coines.mk
